server:
  port: 8085
spring:
  application:
    name: springboot-minio
minio:
  endpoint: http://127.0.0.1:9000
  port: 9000
  accessKey: minioadmin
  secretKey: minioadmin
  secure: false
  bucket-name: commons # 桶名 我这是给出了一个默认桶名
  image-size: 10485760 # 我在这里设定了 图片文件的最大大小
  file-size: 1073741824 # 此处是设定了文件的最大大小
upload: http://127.0.0.1
linux:
  upload:
    path: /usr/local/upload/
visit:
  path: https://www.test.com/minioData